apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "litmus-chapeau.fullname" . }}-as-code
  labels:
    {{- include "litmus-chapeau.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "{{ .Release.Name }}-init-as-code"
      labels:
        {{- include "litmus-chapeau.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "litmus-chapeau.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        imagePullPolicy: Always
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args: ["/app"]
        envFrom:
        - secretRef:
            name: {{ include "litmus-chapeau.fullname" . }}-admin-secret
        env:
          - name: LITMUS_URL
            value: http://{{ include "litmus-chapeau.fullname" . }}-frontend-service.{{ .Release.Namespace }}.svc.cluster.local:{{ index .Values "litmus" "portal" "frontend" "service" "port" }}
          - name: CONFIG_INIT_AS_CODE
            value: {{ .Values.CONFIG_INIT_AS_CODE | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.LOG_LEVEL | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
