apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litmus-chapeau.fullname" . }}-init-as-code
  labels:
    {{- include "litmus-chapeau.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  CONFIG: {{ .Values.CONFIG_INIT_AS_CODE | b64enc | quote }}
